version: '3'
services:
    mongodb:
        image: mongo
        networks:
          - readme_network
        ports:
          - "27017:27017"
    api:
        build:
          context: ..
          dockerfile: ./docker/api/Dockerfile
        networks:
          - readme_network
        ports:
          - "8081:8081"
        links:
          - "mongodb"
        volumes:
          - ./shared_data:/shared_data
    dashboard:
        build:
          context: ..
          dockerfile: ./docker/dashboard/Dockerfile
        networks:
          - readme_network
        ports:
          - "8080:8080"
        links:
          - "mongodb"
        volumes:
          - ./shared_data:/shared_data
networks:
  readme_network:
    driver: bridge
    