version: '3'
services:
    mongodb:
        image: mongo
        networks:
          - readme_network
        ports:
          - "27017:27017"
        volumes:
          - ./mongo:/src/
          - ./mongo_data:/data/db
    mongo_seed:
        build: ./mongo
        links:
          - mongodb
        depends_on:
          - mongodb
        networks:
          - readme_network
    api:
        build:
          context: ..
          dockerfile: ./docker/api/Dockerfile
        networks:
          - readme_network
        ports:
          - "8081:8081"
        links:
          - "mongodb"
        volumes:
          - ./shared_data:/shared_data
    dashboard:
        build:
          context: ..
          dockerfile: ./docker/dashboard/Dockerfile
        networks:
          - readme_network
        ports:
          - "3000:3000"
        links:
          - "mongodb"
        volumes:
          - ./shared_data:/shared_data
networks:
  readme_network:
    driver: bridge
volumes: 
  mongo_data:
