version: '3'
services:
    mongodb:
        image: mongo
        networks:
          - readme_network
        ports:
          - "27017:27017"
        volumes:
          - ./mongo:/src/
          - ./mongo_data:/data/db
    mongo_seed:
        build: ./mongo
        links:
          - mongodb
        depends_on:
          - mongodb
        networks:
          - readme_network
        logging:
          driver: none
    app:
        build:
          context: ..
          dockerfile: ./docker/app/Dockerfile
        networks:
          - readme_network
        ports:
          - "8080:8080"
        links:
          - "mongodb"
        volumes:
          #- ./app/:/app/
          - /app/node_modules
          - ./shared_data:/shared_data
    recommendations:
      build:
        context: ..
        dockerfile: ./docker/recommendations/Dockerfile
      networks:
        - readme_network
      ports:
        - "8081:8081"
      links:
        - "mongodb"
      volumes:
          - ./shared_data:/shared_data
      command: python recommend_articles_for_user.py --mongo mongodb --port 8081
networks:
  readme_network:
    driver: bridge
volumes: 
  mongo_data:
