export var config = {
  host: "http://localhost",
  "db-port": "8080",
  "dashboard-port": "8080",
  loginPath: "/api/login",
  logoutPath: "/api/logout",
  getArticlePath: "/api/getArticle",
  getArticlesPath: "/api/getArticles",
  getFavoritesByUserPath: "/api/getFavorites/user",
  //getFavoritesByArticlePath: "",
  //getCommentsByUserPath: "",
  //getCommentsByArticlePath: "",
  getRequestsByUserPath: "/api/getRequests/user",
  //getRequestsByArticlePath: "",
  getUserPath: "/api/getUser",
  //getUsersPath: "/api/getUsers",
  //newUserPath: "/api/newUser",
  //newArticlePath: "/api/newArticle",
  newFavoritePath: "/api/newFavorite",
  //newCommentPath: "",
  newAnswerPath: "/api/newAnswer",
  updateUserPath: "/api/updateUser",
  //updateArticlePath: "/api/updateArticle",
  powerUserId: "sudo",
  powerUserToken: "NO_TOKEN",
  //newRequest, getAnswers, newAnswer,
};
