export var config = {
  host: "http://localhost",
  "db-port": "8080",
  "dashboard-port": "8080",
  loginPath: "/api/login",
  logoutPath: "/api/logout",
  getArticlePath: "/api/getArticle",
  getArticlesPath: "/api/getArticles",
  getFavoritesByUserPath: "/api/getFavorites/user",
  getRequestsByUserPath: "/api/getRequests/user",
  getRequestsByArticlePath: "/api/getRequests/article",
  getRequestByIdPath: "/api/request/id",
  getUserPath: "/api/getUser",
  newFavoritePath: "/api/newFavorite",
  newAnswerPath: "/api/newAnswer",
  updateUserPath: "/api/updateUser",
  getAnswersByRequestPath: "/api/getAnswers/request",
  powerUserId: "sudo",
  powerUserToken: "NO_TOKEN",
  recommendationsPath: "/api/recommendations",
  deleteFavoritePath: "/api/deleteFavorite",
  getAnswerById: "/api/answer/id",
  newRequestPath: "/api/newRequest",
  getAllOpenRequestsPath: "/api/recommendations/requests",
  newUserPath: "/api/newUser",
  getAnalyticsSitesPath: "/api/analytics/sites",
  getTagsCountPath: "/api/analytics/tags"
  //get recommendations by query?
  //get likes by query
};
